### ISSUE TITLE
Enforce Course uniqueness

### ISSUE THREAD

**Issue by OnlyInAmerica** [FinalsClub/djKarma#102]
Currently, there's nothing preventing the existence of two courses at the same school with the same slug title. This can cause crashes when the server tries to get a course by slug/school (i.e: views.browse_one_course) expecting one result when in fact there are many.

We could remedy this by setting academic_year or semester on Courses and writing model-level validation to ensure a Course slug must be unique for a certain school at a given semester, year.

**Comment by sethwoodworth** [comment]
There is a unique_together function in django models (and in sql)
https://docs.djangoproject.com/en/1.4/ref/models/options/#unique-together

Then we can handle the create exception if adding fails.

Good catch

**Comment by OnlyInAmerica** [comment]
fixed in 22e4cac3ff254. Thanks for the pointer! The current add course form shouldn't allow duplicates to be entered. The few I encountered must have been from way back.

`python manage.py clean_courses` will identify duplicate (school, slug) pairs in Course models, as well as populate required fields with default values (as fix_courses did before).
