### ISSUE TITLE
Anon users cannot create course via modal upload

### ISSUE THREAD

**Issue by OnlyInAmerica** [FinalsClub/djKarma#103]
The add course endpoint requires the user to be logged in.

If an anon user using the upload form attempts to enter a course that does not yet exist, the form will not proceed. 

Create separate course creation endpoint for anon users that validates with captcha?

**Comment by sethwoodworth** [comment]
The best way would be to abstractly add a `response['captcha']` entry whenever we have a user hitting a form while not logged in.  This also suggests that form rendering and handling should have some common methods for pre and post processing.

**Comment by OnlyInAmerica** [comment]
I'll also have to modify the add course form to more resemble the modal upload. As in: We'd have to ask for the School first and filter returned courses on that.
