### ISSUE TITLE
Social Sharing widget

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#12]
- turn new design into modal template
- generate unique invite url hash
- modify registration route to accept/note inviting user
-  _eventually: make registration page that has a different call to action because someone clicked it as an invite, or make the registration page include the KN video_

**Comment by sethwoodworth** [comment]
Finished, but broken.  The bug is now in #32

**Comment by AndrewMagliozzi** [comment]
Let's make this a critical bug.
