### ISSUE TITLE
ReputationEvents

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#164]
We have a fkey to user from a RepEvent and we have a reference from UserProfile to ReputationEvent.

**Comment by CharlesHolbrow** [comment]
UserProfile currently has a many to many relationship with KaramEvents. This is incorrect and redundant. 

ReputationEvents already have a ForeignKey for Actor and User Karma. However, the related_names are unclear. currently they are actor and target. I'm changing them to reputation_event_target and reputation_event_actor. 

Also will be deleting the reputationEvents M2M key in User Profile

**Comment by CharlesHolbrow** [comment]
Consider adding a method to either UserProfile or ReputationEvent that gets all the karma events for a particular user.

**Comment by CharlesHolbrow** [comment]
fixed in refactor Branch
