### ISSUE TITLE
Autocomplete fields css collide with twitter bootstrap

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#19]
ping @OnlyInAmerica, @lingboli

**Comment by OnlyInAmerica** [comment]
There are now entries in styles.less corresponding to the autocomplete list (.ui-autocomplete) and individual dropdown items (.ui-menu-item). There's a basic style added so that the list has a background. Remember to recompile the .less to see these changes effective.

Closed in 178d13c

**Comment by sethwoodworth** [comment]
Totally righteous!
