### ISSUE TITLE
File upload & processing

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#24]
Might be broken.

The current upper limit is 2MB for google to process a document and return html.

But there are a few alternatives we can use:
- GoogleDocs  -- Current baseline
  - Pros: Wide document support. OCR, and translation
  - Cons: Out of our control, 2mb document limit
- LibreOffice cli doc >> html
  - Pros: works on our server, and is a toolchain we can _mostly_ control
  - Cons: It's not very good, and it is likely inconsistent. **Might** not be able to handle .docx
- Hybrid LibreOffice and gdocs
  - **chop docs into pages, upload each page individually**
  - Pro: We can continue to use gdocs
  - Con: Have to bring Libreoffice into the picture at all, and a page might be >2MB anyway
- crocodoc
  - Pros: seems to work well
  - Cons: a software stack we do not control, might not work with annotation
- pdf.js (from mozilla)
  - **renders pdfs as html with javascript**
  - Pro: renders things really really well, seems annotation-able
  - Cons: only works with PDFs AFAIK

**Comment by OnlyInAmerica** [comment]
Just as the baseline: 
- GoogleDocs
  - Pros: Wide document support. OCR, and translation
  - Cons: Out of our control, 2mb document limit

**Comment by sethwoodworth** [comment]
Good idea, added gdocs to top

**Comment by AndrewMagliozzi** [comment]
First I'd like to know what happens when a larger file is uploaded to google.  Does it simply reject it?  If so, how difficult would it be for us to paginate files with OpenOffice and queue them for docs conversion?  I'd still probably institute an 8mb file limit to reduce our server load.  What do you fellas think?

**Comment by sethwoodworth** [comment]
We may reevaluate this at a later date, but the migration to google drive solves 99% of these issues for near-mid future.
