### ISSUE TITLE
Add a Course page

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#30]
Should look a lot like the notes page, include the course info, professor if available, and then list the files associated with the course.

Features for launch:
- ~~activity log for the course (files uploaded mainly)~~
- ~~users who are listed as enrolled in this course~~
- ~~file list~~
- ~~Professor and~~ professor profile if available _could add more professor info_
- ~~add URL for course to interface~~ (and db if not there)
  - add editable field for course if not available, and 'edit this to get karma' prompt #63
- ~~needs style, because this is uuuuuugly~~

Eventually: 
- ~~this page will also include comments ala a facebook wall (time sorted, most recent first messages).~~

**Comment by AndrewMagliozzi** [comment]
Some clarifications:
- The activity log and comments should populate the same "Events" list
- File list should have the same style as the rest of the site
- Course info looks good for now (see notes view page) but could use a
  tweak (ask Andrew)
- Search: it would be awesome if we could have a "search this course"
  option
  - It would return results only for notes in that course repo

**Comment by AndrewMagliozzi** [comment]
I just remembered, we need one important field for this page: LINK TO COURSE WEBSITE

Note that there is good Karma associated with adding that valuable piece of info to a course listing.

https://docs.google.com/a/finalsclub.org/document/d/1t5jYj2LGj-cp85SGM7PNPrOEyhSkNQIOof5urm2_ybM/edit

**Comment by sethwoodworth** [comment]
We need to work out the details of editing course pages, who has access, and if the karma can be gamed.

At a first pass of the site, I'm pretty ok with it being possible to game the karma system for two reasons:
1. I would rather people get access to more karma if they want it, so long as uploading a file is _easier_ than gaming other parts of the site
2. It's going to be really hard to guess how the site might be gamed before we have real users.

**Comment by AndrewMagliozzi** [comment]
Hey Seth, let's discuss at our noon meeting tomorrow.

**Comment by sethwoodworth** [comment]
There is a separate ticket for editing course info, and a discussion to be had there. Closing this ticket in lieu of that one
