### ISSUE TITLE
getting-started page

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#36]
As requested but andrew in #33
- ~~add to site nav~~
- ~~add a default styling like dropbox's by using strikeout on successful completion~~ (using the profile tasks)
- Add a relevance function for different user types (fb users do not probably need to provide a school)
- Link to or describe the task required
- create/list the following tasks
  - ~~Upload a File~~
  - Setup your Profile
  - Select Courses
  - ~~Invite Friends~~
  - View a File
  - Earn Responsibility

**Comment by AndrewMagliozzi** [comment]
It would be extra awesome if each task on the getting started page were a hyperlink to that activity: profile page, upload modal, social modal, etc.

**Comment by sethwoodworth** [comment]
We have an approximation of this page done, enough to launch. I'm moving this to stretch to be re evaluated after tomorrow

**Comment by sethwoodworth** [comment]
Our current design doesn't include a getting-started page.  The tasks system still exists in the repo, but is probably not up to date with the current system structure.  Lets keep this in mind, but remove this issue as a TODO
