### ISSUE TITLE
Karma Police

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#40]
ReputationEvents are translated to a karmic impact in the UserProfile.awardKarma(event_title, target_user) (event_title is the slug title describing the ReputationEventType, like "profile-grad-year" for completing the graduation year section of the profile) method. AwardKarma is called by methods of their corresponding models. These methods are called by views in response to user activity.

~~strikeout~~ indicates complete

TODO:
- ~~disable the karma wall, #71~~
- ~~let karma go into the negative: `UserProfile` migration #72~~
- ~~changed the OWNED tag to VIEWED, and make appear after a file is viewed #73~~
- ~~when a file has been VIEWED, enable the THANK button and hook up karma #74~~
- ~~enable the FLAG button as a `File` flag #75~~

**Comment by AndrewMagliozzi** [comment]
Please reference this link for all "Karma Events"  
https://docs.google.com/a/finalsclub.org/document/d/1t5jYj2LGj-cp85SGM7PNPrOEyhSkNQIOof5urm2_ybM/edit

Here they are reproduced as of the time of this posting.  Note they may have changed slightly so please check the google doc.

# Earning Karma:

## Completing your Profile (Total of 6 Points)
- Username (1 points)
- Picture (1 points)
- Major (1 point)
- School (2 point)
- NEW: Gender (1 point) -- can we pull this from Facebook?

## Uploading Documents
- Study Guide (50 points)
- Note or Summary (10 points)
- Old Exam or Quiz (20 points)
- Assignment (10 points)
- Syllabus (20 points)

## Sharing the Wealth
- Recruiting a new member (5 points)
- Each Study Guide view (15 points to uploader)
- Each Note or Summary view (3 points to uploader)
- Each Exam or Quiz view (5 points to uploader)
- Each Assignment view (3 points to uploader)
- Each Syllabus view (5 points to uploader)

## Weeding the Garden
- Tags (1 point each - up to three tags per document upon upload)
- Link to Course Website (1 point) – must be publicly viewable
- Each “thank” on a document (2 points to uploader)
- Adding new Course or Document Meta Data (1 point per field)

# Losing Karma:

## Viewing Files
- Study Guide (redeem 20 points to view)
- Note or Summary (redeem 5 points to view)
- Old Exam or Quiz (redeem 10 points to view)
- Assignment (redeem 5 points to view)
- Syllabus (redeem 10 points to view)

## Unsuitable Contributions
- Each “flag” on a document (-5 points to uploader) (also -1 to voter)
- Each admin-deleted document (uploader forfeits all document karma) 
- Spamming or other malicious activity (grounds for expulsion)

# Levels and Privileges
- Prospect (10 points) - Search and view documents and thank uploaders
- Beginner (100 points) - Add a school and comment on courses
- Trainee (200 points) - Edit course and note meta data
- Apprentice (500 points) - Flag documents
- Scholar (2000 points) - Moderate documents for your school
- Leader (4000 points) - Edit your school’s CSS

**Comment by sethwoodworth** [comment]
All of the sub tickets are closed. FTW
