### ISSUE TITLE
Improve Karma Events Page

### ISSUE THREAD

**Issue by AndrewMagliozzi** [FinalsClub/djKarma#45]
Chronology: Let's make sure the most recent events are at the top of the page.

Listings: Let's add more details to each listing like DropBox. such as:

You uploaded [File Name + Link] to [Course Name + Link]   

You redeemed [# Karma Points] to view [File Name + Link] for [Course Name + Link]   

You added [Course Name + Link] to your profile

You earned [# Karma Points] for [Reputation Activity]
     - A full table of Reputation Activities and their point values is visible here:

https://docs.google.com/a/finalsclub.org/document/d/1t5jYj2LGj-cp85SGM7PNPrOEyhSkNQIOof5urm2_ybM/edit

**Comment by sethwoodworth** [comment]
You uploaded [File Name + Link] to [Course Name + Link] and earned [# karma]
You redeamed [# karma] to view [filename + link]

**Comment by sethwoodworth** [comment]
This issue is out of date
