### ISSUE TITLE
[search] searching for the same string on search results doesn't make a request

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#46]
I don't know if this is intentional or not.

Steps to repeat:
1. go to the profile page
2. search for 'harvard'
3. search for 'harvard' again

@OnlyInAmerica

**Comment by OnlyInAmerica** [comment]
This is jquery caching at work. I can disable this.

**Comment by sethwoodworth** [comment]
Nope, I would say that is the desired behavior.  +1 for jquery caching.  Closing issue.
