### ISSUE TITLE
gdoc returns inline font styling

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#48]
We can't apply our awesome new fonts unless we strip the inline style from the html that gdocs returns to us.

**Comment by OnlyInAmerica** [comment]
I don't know that we want to muck with the user's font. What if the document is in a foreign language?

As an alternative, we could replace a set of known english fonts with our new font as they occur in the document css.

**Comment by sethwoodworth** [comment]
Replacing _known_ fonts seems like the best plan of action.  Replace default word font Times New Roman with our font style of choice.

But the choice is upto @AndrewMagliozzi, thoughts?

**Comment by AndrewMagliozzi** [comment]
Let's not worry about this for now. Times New Roman will suffice for launch but we should keep this issue open for our next development push.

**Comment by sethwoodworth** [comment]
We wont be able to fix this in the near future without replacing google drive entirely.  This is unfortunate but it is more important to focus on deliverables that effect our users.
