### ISSUE TITLE
[meta] Profile

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#52]
- ~~abandon aliases for facebook users.  Possibly let them use fb username, or first/last name combo~~
- hookup change school and grad year in sidebar #64

Profile page
- add list of 'uncoursed' files below the enrolled courses list

**Comment by AndrewMagliozzi** [comment]
See asana for several critical profile page bugs.

**Comment by sethwoodworth** [comment]
This is now just a dup of #64, closing and continuing on that ticket
