### ISSUE TITLE
Zero-user design pattern upload model

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#55]
The first time a user comes to the site, they need a funnel to getting them uploading documents and registering for the site.

A version of the upload modal should spawn on the front page.  The modal also asks a user to create an account alongside uploading a file.

Upload
- agree to ToS?
- uploads should be stored in the user's session (kept until they lose their cookie)
- uploads should be attached to the user's account once they create an account
- should allow email+pw or facebook account creation

**Comment by sethwoodworth** [comment]
3/4 of this done, and I'm going through testing now on beta

**Comment by sethwoodworth** [comment]
done and done, works on beta

**Comment by AndrewMagliozzi** [comment]
This is great work so far.  But we can make it even better.  Let's talk Sunday about it.
