### ISSUE TITLE
lessc can not compile styles.less

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#6]
```
isforAir:~/code/djKarma/static/less [master*] $ lessc styles.less 
NameError: .opacity is undefined in /home/seth/code/djKarma/static/less/styles.less:269:2
268   .rounded-corners(23px);
269   .opacity(50);
270 
```

According to @lingboli this is probably because the opacity mixin isn't within the scope of lessc since I moved the bootstrap less files.

**Comment by lingboli** [comment]
Styles.less is precompiled into styles.css, so you could just use that as
well. Yeah, prob the mixins less file got moved...

*Lingbo Li

Blog www.LingboLi.com http://www.lingboli.com/
Portfolio www.SaucedMedia.com http://www.saucedmedia.com/
Twitter @LingboLi
*

On Sat, Jun 16, 2012 at 4:20 PM, Seth Woodworth <
reply@reply.github.com
