### ISSUE TITLE
Create disabled state for .button

### ISSUE THREAD

**Issue by OnlyInAmerica** [FinalsClub/djKarma#69]
'Add Course' / 'Finish Upload' action buttons should indicate the validity of their form in their appearance. Let's make a css class .disabled or similar for this.

When the form is valid the button becomes available.

Sound good?

**Comment by sethwoodworth** [comment]
Aye. Sounds like a v1.1 release

**Comment by sethwoodworth** [comment]
We have a .disabled_button class now that we use for a few different things
