### ISSUE TITLE
Connect the THANK and FLAG buttons as ajax functions

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#75]
- THANK should make a karma event
- FLAG should modify the `File` for admin review

**Comment by OnlyInAmerica** [comment]
Thank / Flag connected to the voting system in 9794d3a9. 

Suggestions for next steps:
-  Make a custom admin view to display files with down votes for monitoring.
-  Improve thank / flag feedback. Currently we use jsalert. It would be great to display this feedback with an improved site-wide messaging system.

**Comment by sethwoodworth** [comment]
Done and done, separate ticket for making them pretty.
