### ISSUE TITLE
www.kn.org Deployment checklist

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#76]
**items** means unsure if we need it or install that way
- Install needed apt packages
  - ~~nginx~~
  - ~~postgres~~
  - celeryd -> Some issues with init script.
  - ~~solr~~
  - ~~oracle JVM~~
  - ~~memcached~~
- setup production db
  - ~~import current production to new psql db~~
  - ~~run ./manage.py schemamigration notes --auto; ./manage.py migrate notes~~ Note: karmanotes_beta -> knotes_production
- setup django
  - ~~install pip packages~~
  - ~~add credentials.py file~~ Unless we decide to generate a new one.
- ~~setup solr~~
- add additional tasks to be done
### after final code pushes
- compile less > css `./bin/compilecss.sh` do this before collecting static
- `./manage.py collectstatic` to move static files to the static directory **_must update hardcoded paths for `/var/web/` change**_

**Comment by ghost** [comment]
Only thing not done with this issue. ./manage.py collectstatic to move static files to the static directory must update hardcoded paths for /var/web/ change
