### ISSUE TITLE
Make a ViewedFile class

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#77]
This will let us quickly generate the viewed/not viewed status of files on the course page.

fkey to: 
- user
- course
- file
  then when dispalying course files, 

use like:

```
ViewedFiles.objects.filter(course=course).(fileter(user=user).all()
```

return list of viewedFiles ids and pass it to the template

```
{% if file.id in user_viewed_files %} ...
```

**Comment by OnlyInAmerica** [comment]
I like this idea.

As a stopgap, or improvement in other areas where we make many queries in an iterative fashion, Django's [select_related](https://docs.djangoproject.com/en/dev/ref/models/querysets/#select-related) function may be of use in improving performance.

**Comment by sethwoodworth** [comment]
@CharlesHolbrow covered this with his modification of the views.file function conditional view saving and with a karma event
