### ISSUE TITLE
on username register, require email address

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#84]

**Comment by OnlyInAmerica** [comment]
I've got this covered. Will commit the change this evening.

**Comment by AndrewMagliozzi** [comment]
sweet

**Comment by sethwoodworth** [comment]
#e01b7e38 done!

**Comment by sethwoodworth** [comment]
https://github.com/FinalsClub/djKarma/commit/e01b7e38f1e5189d6a37fe0b8a128bc55a58ecbc#KNotes/templates/registration/register.html
