### ISSUE TITLE
Widgetize upload wizard

### ISSUE THREAD

**Issue by sethwoodworth** [FinalsClub/djKarma#9]
- AJAX: University search endpoint
- AJAX: Course title search endpoint
- Form: File type radio buttons should select metadata fields
- Conditional: if new course, ask if they are currently in class

**Comment by OnlyInAmerica** [comment]
AJAX search endpoints are available:
- University: notes.views.schools
- Course: notes.views.courses

Both methods take a GET parameter 'q' with the search string and return a JSON array of (model.title, model.pk) tuples.

**Comment by sethwoodworth** [comment]
Duplicate of #25 `modal_upload behavior`
